.PHONY: build setup run

build:
	@echo "Building Go binary and setting up filesystem..."
	bash fs.sh

setup:
	@echo "Running setup script..."
	bash setup.sh

run:
	@echo "Running Go program..."
	go run main.go 